"""Initial Migration

Revision ID: 655997557eb7
Revises: 16fb80f175f8
Create Date: 2019-11-26 10:30:18.002304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655997557eb7'
down_revision = '16fb80f175f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
