"""add a pass_hash to user model

Revision ID: 7abf012504ed
Revises: 0c2902a8066c
Create Date: 2019-11-25 08:53:41.235076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abf012504ed'
down_revision = '0c2902a8066c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###
